services:
  plantuml-server:
    image: plantuml/plantuml-server:jetty
    ports:
      - "8080:8080"
    restart: always
  
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d my_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    volumes:
      - ./:/app:cached
    environment:
      # アプリ内やAlembicで使う接続URL
      DATABASE_URL: "postgresql://user:password@db/my_db"
    working_dir: /app
    env_file:
      - .env
    ports:
      - 127.0.0.1:${PORT}:8501
    tty: true
    depends_on:
      db:
        condition: service_healthy