"""initial_schema

Revision ID: 7ed5ad2ac5d4
Revises: 
Create Date: 2026-04-21 22:00:46.853880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed5ad2ac5d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pclass', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('slibSp', sa.Integer(), nullable=True),
    sa.Column('parch', sa.Integer(), nullable=True),
    sa.Column('ticket', sa.String(length=255), nullable=True),
    sa.Column('fare', sa.Float(), nullable=True),
    sa.Column('cabin', sa.String(length=255), nullable=True),
    sa.Column('embarked', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persons')
    # ### end Alembic commands ###
